version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "127.0.0.1:8013:80"
        volumes:
            - ./code:/code:ro
            - ./site.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - code-network
    php:
        read_only: true
        image: php:fpm
        volumes:
            - ./code:/code:ro
            - ./flag:/flag:ro
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
