version: '2.2'

services:
    web:
        image: nginx:latest
        ports:
            - "127.0.0.1:8007:80"
        volumes:
            - ./code:/code:ro
            - ./site.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - code-network
    php:
        read_only: true
        build: .
        volumes:
            - ./code:/code:ro
            - ./db:/db:ro
            # - type: tmpfs
            #   target: /tempdb
              #read_only: true
        networks:
            - code-network

        # limit to 10 GB! of RAM cos apparently sqlmap abuses our poor RAM
        mem_limit: 10000000000
        memswap_limit: 0
        cpu_count: 1
        cpu_percent: 50
        cpu_shares: 50
        cpuset: 0,1


networks:
    code-network:
        driver: bridge
