"""empty message

Revision ID: dcf4e70b0b6f
Revises: d5a224bf5862
Create Date: 2018-01-21 22:58:18.178098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf4e70b0b6f'
down_revision = 'd5a224bf5862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('is_first_year', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('is_tcd_student', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'is_tcd_student')
    op.drop_column('teams', 'is_first_year')
    # ### end Alembic commands ###
