version: '2'

services:
  ctfd:
    build: .
    restart: always
    ports:
      - "127.0.0.1:9000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      # - DATABASE_URL=postgres://ctfd:ctfd@db/ctfd
    volumes:
      - .data/CTFd/logs:/opt/CTFd/CTFd/logs
      - .data/CTFd/uploads:/opt/CTFd/CTFd/uploads
      # - ./:/opt/CTFd
    depends_on:
      - db

  db:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD=ctfd
  #     - POSTGRES_USER=ctfd