version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "127.0.0.1:8001:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: .
        image: php:fpm
        volumes:
            - ./code:/code
        networks:
            - code-network
    db:
        image: mysql:latest
        restart: always
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_DATABASE: tidal
            MYSQL_USER: tidal
            MYSQL_PASSWORD: t1d3p0dzzzz
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
