version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "127.0.0.1:8009:80"
        volumes:
            - ./code:/code:ro
            - ./site.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
